language: r
cache: packages

r_packages:
  - devtools

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

deploy:
    provider: netlify
    site:

    local_dir: docs
    skip_cleanup: true
    keep-history: true
    github_token: $TRAVISCI
    repo: Hendrik147/HR_Analytics_in_R_book_v2
    target_branch: gh-pages
    on:
      branch: master
